#!/usr/bin/env node
import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p));
const shells=json('data/hotline-shells.json');
const idx=json('syndicates/generated/lou-vega/archive/index.json');
const issue=idx.issues.find(x=>x.id==='2026-08-30T0930|lou-vega');
assert(issue?.shellVersion===3,'Historical Lou issue must retain v3');
const pizza=json(issue.pizzaPlay.archivePath);
assert.equal(issue.pizzaPlay.vigScopeStatus,pizza.play.vigScopeStatus);
assert.equal(issue.pizzaPlay.selectionKey,pizza.play.feed.selectionKey);
assert.equal(issue.sourceReport,pizza.source.reportPath);
const report=json(issue.sourceReport),archive=read(`syndicates/generated/lou-vega/archive/${issue.path}`);
assert.equal(report.label,issue.label);
const counts=`${report.counts.bet} BET · ${report.counts.lean} LEAN · ${report.counts.wait} WAIT · ${report.counts.pass} PASS · $${report.risk}`;
for(const m of ['data-shell-version="3"','PIZZA PLAY #1',pizza.play.title.toUpperCase(),counts])assert(archive.includes(m),`Historical Lou archive missing ${m}`);
const reg=shells.shells.find(x=>x.characterId==='lou-vega' && x.version===3);
assert(reg && reg.defaultForCharacter===false,'Preserve the historical v3 registry without making it current');
const shell=read('syndicates/generated/lou-vega/shell-v3.html');
for(const m of ['{{RECOMMENDATION_ITEMS}}','04_lou_vega_header_banner.png','03_vegas_by_the_slice_logo.png','02_lou_vega_portrait_cutout.png','01_lou_vega_main_hero.png','{{LAST_STOP}}'])assert(shell.includes(m),`Historical v3 shell missing ${m}`);
console.log('LOU VEGA: historical v3 shell, report and Pizza selection preserved');
