import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const json=p=>JSON.parse(read(p));
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
const profile=json('data/characters/eddie-numbers.json');
const roster=json('data/syndicates.json');
const shells=json('data/hotline-shells.json');
const live=read('syndicates/sharp-room/incoming.html');
const fallback=json('data/bet-history-public.json');
assert(profile.authority?.mode==='ledger-authoritative','Eddie must be ledger-authoritative');
assert(profile.authority?.source==='/api/bet-history','Eddie authority source must be /api/bet-history');
assert(profile.authority?.actualDollars===true,'Eddie must use actual CAD dollars');
assert(profile.authority?.fictionalScaling===false,'Eddie fictional scaling must be disabled');
assert(roster.profiles.find(x=>x.characterId==='eddie-numbers')?.title==='MUDDY NUMBERS // LEDGER DESK','Eddie roster title not converted');
assert(roster.slots[0]?.title==='MUDDY NUMBERS // LEDGER DESK','Eddie slot title not converted');
assert(shells.shells.find(x=>x.id==='muddy-ledger-desk'&&x.defaultForCharacter===true),'Muddy Ledger Desk shell is not default');
for(const marker of ['ACTUAL CAD DOLLARS','CASH-WAGER CUMULATIVE P/L','WEEKLY + MONTHLY RECONCILIATION','Sport Desk','Sportsbook Windows','MUDDY METERS','MUDDY LEDGER // LAST 10 TICKETS','EDDIE: WHAT THE NUMBERS SAY','THE WALK TO THE CAGE']) assert(live.includes(marker),`Missing Ledger Desk marker: ${marker}`);
assert(live.includes("const URL='/api/bet-history'"),'Live desk must fetch /api/bet-history');
assert(!live.includes('../../data/betting-ledger.json'),'Live desk still exposes raw public-ledger path');
assert(live.includes("cache:'no-store'"),'Ledger fetch must bypass browser cache');
assert(fallback.publicProjection===true,'Static fallback must remain sanitized');
assert(Array.isArray(fallback.wagers)&&fallback.wagers.length>0,'Fallback wagers missing');
assert(fallback.wagers.every(r=>r[2]===null),'Fallback sportsbook reference leaked');
console.log('MUDDY NUMBERS // PRIVATE LEDGER DESK guardrails: PASS');
